name: Workflow
on: push
jobs:
  build:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile